### ISSUE TITLE
Drive to small error with NVMe drives

### ISSUE THREAD

**Issue by Xara** [extremeshok/xshok-proxmox#20] opened 2019-06-29 06:28 UTC
Hello, your scripts don't work with nve drives, yet less with already initialised software raid. When installation script come to check drives, of course it fail with "drive to small" error as those drivers aren't  sd* ones .
drivers are type /dev/nvme0n1 and /dev/nvme1n1 for 2 drives system

**Comment by extremeshok** [comment] 2019-07-31 01:40
working on a fix which will have nvme support

**Comment by extremeshok** [comment] 2019-07-31 01:40
duplicate of  #6

**Closed by extremeshok** 2019-07-31 01:41 UTC
